url: "https://buditanrim.co" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Budi Tanrim" # the name of your site, e.g. ACME Corp.
description: Budi Tanrim's blog on design, mindset, and frameworks
twitter_username: buditanrim
permalink: /:year/:title/
repository: buditanrim/buditanrim.github.io
future: false
timezone: Asia/Bangkok

#SEO
twitter:
  username: buditanrim
  card: summary_large_image

collections: 
  projects:
    output: true
    permalink: /:title

# Build settings
markdown: kramdown
exclude: ['_site']
plugins:
  - jekyll-feed