name: CI

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Jekyll Publish Drafts
      uses: soywiz/github-action-jekyll-publish-drafts@master
      with:
        github_token: ${{ secrets.9997d46aa0431fbfbd9bead2a99df49867add16f }}
        jekyll_path: ./
        branch: staging-budi